### ISSUE TITLE
Migrar projeto para haml.

### ISSUE THREAD

**Issue by hpcarlos** [renatoramiro/thorp#2]
O que acha de mudar o projeto de erb para haml?

Eu particularmente não gosto de usar erb, e a grande maioria dos desenvolvedores usam haml.

se estiver disposto a usar o haml, eu posso fazer a migração de todo o código e enviar.

**Comment by jonathanccalixto** [comment]
se precisar de alguma ajuda estarei aqui

**Comment by hpcarlos** [comment]
O lance principal neste projeto creio que nem seja desenvolver uma ferramenta completa, mas para estudo das pessoas que estão envolvidas.

Temos que esperar o Renato Ramiro responder, tudo depende dele.

**Comment by renatoramiro** [comment]
Nunca utilizei o haml, mas já que é tendência da maioria de railers, acho que vale a pena migrarmos.

**Comment by jonathanccalixto** [comment]
@hpcarlos eu entendi que este projeto é mais para estudo, pois isso que eu gostaria de participar, se @renatoramiro me permitir, eu gostaria muito, pois sei que assim irei aperfeiçoar meus conhecimento, e passar o conhecimentos que eu possuo.

**Comment by renatoramiro** [comment]
@jonathanccalixto já está 'permitido'. Só vou precisar da ajuda de vocês, porque sou meio noob em git.

**Comment by hpcarlos** [comment]
Tranquilo Renato, agora e só você ir postando as necessidades que o povo vai ajudando e enviando as mudanças para você aplicar.

Em quanto isso você vai fazendo suas mudanças.

**Comment by hpcarlos** [comment]
projeto migrado para HAML.
